version: '3.7'
services:
  yoptascript-docker-isolation-provider:
    image: deepf/yoptascript-docker-isolation-provider:main
    networks:
      - deep
    ports:
      - 3020:3020
    restart: always
    environment: {}
networks:
  deep:
    driver: bridge
